model:
  name_or_path: google/flan-t5-small
  save_dir: model/baseline_v1.2
  version: baseline_v1.2

data:
  train_path: data/train_2k_5types.json
  test_path: data/test_pairs.json
  val_ratio: 0.1
  max_length: 64

training:
  lr_scheduler_type: linear
  warmup_steps: 500
  epochs: 10
  batch_size: 16
  learning_rate: 0.00003
  fp16: false
  logging_steps: 50
  save_total_limit: 2

inference:
  num_beams: 8
