model:
  name_or_path: google/flan-t5-small
  save_dir: model/polite-rewriter
  version: baseline_v0

data:
  train_path: data/polite_pairs.json
  test_path: data/test_pairs.json
  val_ratio: 0.1
  max_length: 64

training:
  epochs: 8
  batch_size: 8
  learning_rate: 0.00003
  fp16: true
  logging_steps: 50
  save_total_limit: 2

inference:
  num_beams: 5
